manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob/zmk
    - name: k3d3
      url-base: https://github.com/k3d3/zmk
  projects:
    - name: zmk
      remote: k3d3
      revision: main
      import: app/west.yml
  self:
    path: config
